FROM python:3.10

ARG UID=1000
ARG GID=1000

RUN apt update
RUN apt upgrade -y
RUN apt install ffmpeg libsm6 libxext6 libzbar-dev -y
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

WORKDIR /app

RUN groupadd -g "${GID}" -r pcr-people-detect \
    && useradd -d '/app' -g pcr-people-detect -l -r -u "${UID}" pcr-people-detect \
    && chown pcr-people-detect:pcr-people-detect -R '/app'

USER pcr-people-detect
